daemonset:
  image:
    repository: postfinance/kubenurse
    # tag: v1.7.0 # uncomment if you want to manually specify the tag
  extraEnvs: []
  podLabels: {}
  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  containerResources: {}
  containerImagePullPolicy: IfNotPresent
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Equal
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Equal
  dnsConfig: {}
  volumeMounts: []
  volumes: []
  priorityClassName: ""

serviceMonitor:
  enabled: false
  labels: {}

# environment variables
#
# KUBENURSE_INSECURE
insecure: true
# KUBENURSE_SERVICE_URL
service_url: ""
# KUBENURSE_ALLOW_UNSCHEDULABLE
allow_unschedulable: false
# KUBENURSE_NEIGHBOUR_FILTER
neighbour_filter: app.kubernetes.io/name=kubenurse
# KUBENURSE_NEIGHBOUR_LIMIT
neighbour_limit: 10
# KUBENURSE_HISTOGRAM_BUCKETS
histogram_buckets: ""
# histogram_buckets: ".0005,.001,.0025,.005,.01,.025,.05,0.1,0.25,0.5,1" # default prometheus histogram buckets divided by 10
# KUBENURSE_EXTRA_CA
extra_ca: ""
# KUBENURSE_CHECK_API_SERVER_DIRECT
check_api_server_direct: true
# KUBENURSE_CHECK_API_SERVER_DNS
check_api_server_dns: true
# KUBENURSE_CHECK_ME_INGRESS
check_api_me_ingress: true
# KUBENURSE_CHECK_ME_SERVICE
check_api_me_service: true
# KUBENURSE_CHECK_NEIGHBOURHOOD
check_neighbourhood: true
# KUBENURSE_CHECK_INTERVAL
check_interval: 5s
# KUBENURSE_REUSE_CONNECTIONS
reuse_connections: false
# KUBENURSE_SHUTDOWN_DURATION
shutdown_duration: 5s
# KUBENURSE_USE_TLS
use_tls: false
# KUBENURSE_CERT_FILE
cert_file: ""
# KUBENURSE_CERT_KEY
cert_key: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

service:
  name: 8080-8080
  port: 8080
  labels: {}

ingress:
  enabled: true
  className: nginx
  # KUBENURSE_INGRESS_URL
  url: dummy-kubenurse.example.com
